import type { Metadata } from 'next'

import './globals.css'
import AppState from './context/appState';


export const metadata: Metadata = {
  manifest:"/manifest.json",
  title: 'Ecommerce Site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <AppState>
        {children}
        </AppState>
        </body>
    </html>
  )
}
